### ISSUE TITLE
React Router-like lib and routing with Cycle.js

### ISSUE THREAD

**Issue by DjebbZ** [jsforum/jsforum#4]
Hello,

I don't know if this is the place to ask you a question, excuse me for the noise if it isn't.

I'm wondering how to do routing properly with Cycle.js. From my understanding of it, there should be some 'history Driver' that outputs an Observable of url changes and takes as input another Observable of the same kind to affect the browser. I didn't find an example in the cycle-examples repo though.

Also, I find React Router (and all similar libs) really nice to describe the shape of the UI for a given URL. Do you know if a similar project for Cycle.js exists/is feasible ?

Thanks in advance for the pointers !

**Comment by tomek-he-him** [comment]
Looking by https://github.com/jsforum/jsforum/commit/67b596b0dfcf9f9fb98239f10218fc063a5847e0 it’s not a place for such things.

I can’t help you (I don’t use React) – but https://stackoverflow.com definitely can.

**Comment by DjebbZ** [comment]
Ok, gonna close then. I took it as a place to discuss with Andre, but in fact my question was about Cycle.js. Sorry again for the noise.

**Comment by troch** [comment]
Long discussion here: https://github.com/cyclejs/cycle-core/issues/159

**Comment by DjebbZ** [comment]
Awesome discussion, thanks a lot.
